upstream overseer_web {
    server 127.0.0.1:8000;
}


server {
    server_name dashboard.overseer.so;

    client_max_body_size 64k;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location /static/ {
        alias /opt/overseer/src/web/static/;
        expires 1h;
        access_log off;
    }

    location / {
        proxy_pass http://overseer_web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;

        proxy_connect_timeout 5s;
        proxy_send_timeout 35s;
        proxy_read_timeout 35s;
    }

    listen [::]:443 ssl ipv6only=on; 
    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/dashboard.overseer.so/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/dashboard.overseer.so/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}



server {
    if ($host = dashboard.overseer.so) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 default_server;
    listen [::]:80 default_server;
    server_name dashboard.overseer.so;
    return 404; # managed by Certbot


}